import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Typography } from "@mui/material";
import FormComponent from "@/components/customComponent/ReusableForm";
import Footer from "../components/footer";
import Reviewer from "@/components/reviewer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <FormComponent title="Get your Seat" bg="https://picsum.photos/500/700" />
      <Footer /> */}
      <Reviewer
        bgImg="/ds"
        title="Great place, friendly atmosphere, very delicious food (especially Brownies). Also here you can buy flowers also. Totally recommend 10/10"
      />
    </>
  );
}
