import Head from "next/head";
import localFont from "next/font/local";
import { Stack } from "@mui/material";
import HomePage from "@/components/home";
import React from "react";

const myFont = localFont({ src: "../assets/fonts/Athena.ttf" });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack
        sx={{
          background:
            "linear-gradient(137.15deg, #000000 37.02%, rgba(112, 80, 88, 0.844253) 72.16%, #EC9FB6 103.65%)",
          height: "100vh",
        }}
      >
        <HomePage />
      </Stack>
    </>
  );
}
